name: Run Twitter Telegram Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # каждые 30 минут
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Download previous posted_texts.json from artifact
        uses: actions/download-artifact@v3
        with:
          name: posted-texts
        continue-on-error: true

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python bot.py

      - name: Upload updated posted_texts.json to artifact
        uses: actions/upload-artifact@v3
        with:
          name: posted-texts
          path: posted_texts.json
