name: Run Twitter Telegram Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # ⏰ Запуск каждые 30 минут (UTC)
  workflow_dispatch:        # 🔘 Возможность ручного запуска из интерфейса GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout репозитория
        uses: actions/checkout@v3

      - name: ⚙️ Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: 📦 Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: ⬇️ Загрузка предыдущего posted_texts.json
        uses: actions/download-artifact@v3
        with:
          name: posted-texts
        continue-on-error: true

      - name: 🚀 Запуск бота
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python bot.py

      - name: ⬆️ Сохранение обновлённого posted_texts.json
        uses: actions/upload-artifact@v3
        with:
          name: posted-texts
          path: posted_texts.json
