name: Run Twitter Fetch Bot

on:
  schedule:
    - cron: '0 * * * *'  # каждый час
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore posted_texts.json cache
        uses: actions/cache@v4
        with:
          path: posted_texts.json
          key: posted-texts-${{ github.run_id }}
          restore-keys: |
            posted-texts-

      - name: Run bot
        run: python bot.py

      - name: Save posted_texts.json cache
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: posted-texts
          path: posted_texts.json
