name: Run Twitter to Telegram Bot

on:
  schedule:
    - cron: '0 * * * *'  # каждый час
  workflow_dispatch:     # запуск вручную

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install playwright certifi
          python -m playwright install

      - name: Run the bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          export SSL_CERT_FILE=$(python -m certifi)
          python bot.py
