name: Run Twitter Fetch Bot

on:
  schedule:
    - cron: '0 * * * *'  # каждый час
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Настроить Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Установить зависимости
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Восстановить кэш posted_texts.json
      uses: actions/cache@v4
      with:
        path: posted_texts.json
        key: posted-texts-${{ github.run_id }}
        restore-keys: posted-texts-

    - name: Запустить бот
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: |
        python bot.py
